### PR TITLE
Dojo editor fixes

### LINKED ISSUE #93: Sitemap property editable for languages that are not the master language
I have the following code in PageType

```c#
[UIHint("SeoSitemap")]
[BackingType(typeof(PropertySEOSitemaps))]
[Display(Name = "Sitemap settings")]
public virtual string SeoSitemaps { get; set; }
```

Expected result:
I can only edit the property when on the master language.

Actual result:
When I view the property in edit-mode on a language version of that site that is not master, I will be able to change the property.
bug

### PR DESCRIPTION
**Pull request by jarihaa**
- Fixes #93 
- Fixes enabled checkbox being checked even if the value is false.

### CODE REVIEW

**Comment by jarihaa** [comment]
- Disable editor when language is not master language and property is not culture specific. #93
- Fix enabled checkbox status.
- Fix comparison #95

**Comment by dinoo** [comment]
Thanks @jarihaa !

**Comment by dinoo** [comment]
Thanks @jarihaa !

**Comment by frederikvig** [comment]
Thanks jarihaa

**Pull request merged**
