### PR TITLE
Fix for issue 37: Parse Accept-Encoding

### PR DESCRIPTION
**Pull request by fatso83**
In #37 we documented that this module did not handle Accept-Encoding according to spec, pushing
out compressed content to clients that did not understand how to handle it (`curl`, for instance).

This pull requests adds the required logic to handle this, and can also decide the best encoding to use based on the weights given to the accepted encodings by the client.

This also adds support for `deflate` compression.

### CODE REVIEW

**Comment by fatso83** [comment]
I was a bit unsure on how to structure the project, so I can change this according to how you like it, if need be. This is the first time I dip my toes in a .NET project, so these are the points I would assume you might have something to add to, as I am not intimately familiar with the culture:

- project structure (currently unit tests as separate project)
- namespacing (just used a root `UnitTests` namespace)
- some test "duplication" (not really, but perhaps covers the same ground?)

**Comment by frederikvig** [comment]
Thanks for this. Some comments: Could you move the test projects to a test folder and rename the project to Geta.SEO.Sitemaps.Tests. Make sure method names are PascalCase.

**Comment by fatso83** [comment]
@frederikvig: Thanks for reviewing.. I have just seen that a lot of (most?) people mix unit tests and integration tests, making running tests frequently unpleasant, which is why I often decide to keep two different projects. I'll rename it, np. Coming from Java I haven't yet developed an instinctive aversion to camel casing yet, so I completely missed that 🤓

**Comment by fatso83** [comment]
All change requests implemented. Build and tests are still green :-)

**Comment by frederikvig** [comment]
The test project should be placed in a test folder and the project name should be Geta.SEO.Sitemaps.Tests. So it will look something like this: test/Geta.SEO.Sitemaps.Tests/. I also noticed that there were some regions in the code, could you remove those as well? Thanks!

**Comment by fatso83** [comment]
Ah, misunderstood you on the directory move. Had yet to see that layout in .NET projects, but aligns nicely with the directory layouts of other coding cultures I am more used to. Fixed.
Regions removed as well.

**Pull request merged**
